[package]
name = "user-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.5.0"
axum = "0.7.2"
axum-prometheus = "0.5.0"
axum-route-error = "5.0.0"
tonic = "0.10.2"
prost = "0.12.3"
prost-types = "0.12.3"
tokio = { version = "1.35.0", features = ["rt-multi-thread", "macros"] }
serde = "1.0.193"
serde_json = "1.0.108"
serde_derive = "1.0.192"
sqlx = { version = "0.7.3", features = [ "runtime-tokio", "postgres", "chrono", "tls-rustls" ] }
dotenvy = "0.15.7"
chrono = { version = "0.4.31", features = [ "serde" ] }
url = "2.4.1"
anyhow = "1.0.75"
log = "0.4.20"
once_cell = "1.18.0"
prometheus = "0.13.3"
derive_more = { version = "1.0.0-beta.6", features = ["display", "constructor", "from", "error"] }
thiserror = "1.0.51"
autometrics = { version = "1.0.0", features = ["prometheus-exporter"] }

[dev-dependencies]
testcontainers = "0.15.0"

[build-dependencies]
tonic-build = "0.10.2"
